# Generated by Django 5.0.6 on 2024-05-23 11:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=1000, verbose_name='Поисковой запрос')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('closed', models.DateTimeField(blank=True, null=True, verbose_name='Время закрытия')),
                ('is_close', models.BooleanField(default=False, verbose_name='Открыт/Закрыт')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Искатель')),
            ],
            options={
                'verbose_name': 'Заявка поиска',
                'verbose_name_plural': 'Заявки поиска',
                'ordering': ('-created', 'is_close'),
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('bonus', models.IntegerField(default=0, verbose_name='Бонус')),
                ('promo', models.IntegerField(default=0, verbose_name='Промокод')),
                ('photo', models.URLField(verbose_name='Ссылка на фотографию')),
                ('link', models.URLField(verbose_name='Ссылка на товар')),
                ('real_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, verbose_name='Итоговая сумма')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='management.order', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Карточка товара',
                'verbose_name_plural': 'Карточки товара',
                'ordering': ('real_price',),
            },
        ),
    ]
