# Generated by Django 5.0.6 on 2024-05-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_search',
            field=models.DateTimeField(auto_now=True, verbose_name='Время последнего обновления'),
        ),
    ]
