# Generated by Django 5.0.6 on 2024-05-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_order_id_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='closed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время закрытия'),
        ),
    ]
