# Generated by Django 5.0.6 on 2024-05-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_order_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AlterField(
            model_name='card',
            name='real_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, verbose_name='Итоговая сумма'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
